### ISSUE TITLE
Error: ENOENT: no such file or directory, lstat '/app/Roboto-Black.ttf'

### ISSUE THREAD

**Issue by Not-found-squad** [squarfiuznath/discanvas#4]
![Screenshot_20210511_132752](https://user-images.githubusercontent.com/80631396/117768792-10e3cf80-b25d-11eb-933c-3cff4b13345b.jpg)

Error: ENOENT: no such file or directory, lstat '/app/Roboto-Black.ttf'
    at Object.realpathSync (fs.js:1728:7)
    at Object.registerFont (/app/node_modules/canvas/index.js:48:34)
    at Object.<anonymous> (/app/node_modules/discanvas/canvas/rankcard.js:2:8)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/app/node_modules/discanvas/index.js:9:27) {
  errno: -2,
  syscall: 'lstat',
  code: 'ENOENT',
  path: '/app/Roboto-Black.ttf'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! api-zhirrr@1.1.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the api-zhirrr@1.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /app/.npm/_logs/2021-05-11T06_27_12_014Z-debug.log

Help

**Comment by squarfiuznath** [comment]
I checked my code and indeed it may work for some and not for others, so I'll correct that right now and thank you for reporting it. I'll let you know when I update so you can reinstall the package.

**Comment by squarfiuznath** [comment]
It's ok, I fixed the problem, reinstall the module on your host. If the problem persists I don't think the problem is mine :/

**Comment by pauldb09** [comment]
You can register the font using a cdn
